feat(bot-analytics): setup CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -285,7 +285,50 @@ jobs:
         name: test-results-bot-failing-offer
         path: packages/bot-failing-offer/coverage-tests-report.json
 
-  # ==== End job: bot-failing-offer ====        
+  # ==== End job: bot-failing-offer ====
+  #
+  #  # ==== Job: Build and test bot-analytics ====
+  bot-analytics:
+    runs-on: ubuntu-latest
+
+    env:
+      working-directory: packages/bot-analytics
+
+    defaults:
+      run:
+        working-directory: ${{env.working-directory}}
+
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v3
+
+    - name: Yarn setup (caching yarn dependencies)
+      uses: actions/setup-node@v3
+      with:
+        node-version: 18.x
+        cache: 'yarn'
+
+    - run: yarn install --immutable
+      working-directory: . # Yarn must run in root to ensure monorepo setup
+
+    - name: Foundry Setup
+      uses: ./.github/actions/foundry-setup
+      
+    - name: Build
+      id: build
+      run: yarn run build
+
+    # == run and report tests == 
+    - name: Test
+      run: yarn run test:coverage
+
+    - uses: actions/upload-artifact@v2
+      if: ${{ steps.build.conclusion == 'success' && (success() || failure())}}
+      with:
+        name: test-results-bot-analytics
+        path: packages/bot-analytics/coverage-tests-report.json
+
+  # ==== End job: bot-failing-offer ====       
 
   # ==== Job: Build and test Mangrove arbitrage contract ====
   mangrove-arbitrage-contract:
